#! /bin/sh

sxhkd &
nitrogen --restore &
polybar example &

bspc monitor -d main web video IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Make windows float on specific desktops
# https://github.com/baskerville/bspwm/issues/325
bspc subscribe node_manage | while read event monitor desktop nodeid ipid; do
	case "$desktop" in
		video|6||7|9)
			bspc node "$nodeid" --state floating
			;;
	esac
done &

bspc rule -a Chromium desktop=^2
bspc rule -a mpv desktop=^3
